name: HTML Check

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@<latest version>
      with:
        root: /
        
    - name: stylelint 
    - uses: actions-hub/stylelint@master
        
    - uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log
