name: HTML Check

on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: HTML5Validator
      uses: Cyb3r-Jak3/html5validator-action
      with:
        root: /
        

    - name: stylelint
      uses: actions-hub/stylelint@master
